### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)'

### ISSUE THREAD

**Issue by tiholic** [cnhefang/image_picker_saver#15]
I/flutter (22005): _onImageSaveButtonPressed http://192.168.0.113:8081/media/uploads/ideaspace/IMG-20190207-WA0014.jpg
I/flutter (22005): 200
D/DecorView(22005): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@168be4a[MainActivity]
D/AndroidRuntime(22005): Shutting down VM
E/AndroidRuntime(22005): FATAL EXCEPTION: main
E/AndroidRuntime(22005): Process: com.coromandel.ideaspace, PID: 22005
E/AndroidRuntime(22005): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=0, data=null} to activity {com.coromandel.ideaspace/com.coromandel.ideaspace.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(22005): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4496)
E/AndroidRuntime(22005): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4538)
E/AndroidRuntime(22005): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime(22005): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(22005): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(22005): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
E/AndroidRuntime(22005): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(22005): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(22005): 	at android.app.ActivityThread.main(ActivityThread.java:6863)
E/AndroidRuntime(22005): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22005): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/AndroidRuntime(22005): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime(22005): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(22005): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.finishWithSuccess(ImagePickerDelegate.java:481)
E/AndroidRuntime(22005): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:401)
E/AndroidRuntime(22005): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:375)
E/AndroidRuntime(22005): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:210)
E/AndroidRuntime(22005): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:139)
E/AndroidRuntime(22005): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:138)
E/AndroidRuntime(22005): 	at android.app.Activity.dispatchActivityResult(Activity.java:7476)
E/AndroidRuntime(22005): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4489)
E/AndroidRuntime(22005): 	... 11 more
D/OSTracker(22005): OS Event: crash
I/Process (22005): Sending signal. PID: 22005 SIG: 9
Lost connection to device.

**Comment by cnhefang** [comment]
I need more information to know how this error happened, just like the steps, system, environment

**Comment by tiholic** [comment]
@cnhefang It was a simple download and save to device similar to the one as given in the example (just variables changed, like URL and device destination file path)

One Plus 5t on Oxygen OS. Android 9
