### ISSUE TITLE
Unhandled Exception: Invalid argument(s)

### ISSUE THREAD

**Issue by muss01** [cnhefang/image_picker_saver#20]
`[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Invalid argument(s)
E/flutter (18097): #0      _StringBase.+ (dart:core-patch/string_patch.dart:260:57)
E/flutter (18097): #1      ImagePickerSaver.saveFile (package:image_picker_saver/image_picker_saver.dart:85:34)`

Am using the permission storage in `AndroidManifest.xml`

`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>`
`<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>`

But the application doesn't ask me for the permission

**Comment by pasha009** [comment]
I got similar Unhandled Exception in some unrelated project. It turned out that it was because i was trying to concatenate a string and null object. 
Just sharing my reason of having this error...

**Comment by nandin-borjigin** [comment]
I don't know why the repo author commented this line out.

https://github.com/cnhefang/image_picker_saver/blob/19cdd80dab8e9c4b25a5029d9d1f67b539ae92c2/ios/Classes/ImagePickerSaverPlugin.m#L129

It causes [`channel.InvokeMethod`](https://github.com/cnhefang/image_picker_saver/blob/bc459010d10228509282a4ad8c8d8edb12612dce/lib/image_picker_saver.dart#L77) on dart side to return null and [concatenating a string with a null value](https://github.com/cnhefang/image_picker_saver/blob/bc459010d10228509282a4ad8c8d8edb12612dce/lib/image_picker_saver.dart#L85) would throw an 'Invalid arugment(s)' exception.
