### ISSUE TITLE
Flutter 1.7.8+hotfix.3 breaks ability to get camera/gallery image.

### ISSUE THREAD

**Issue by bhurlbert** [cnhefang/image_picker_saver#22]
The latest Flutter/Dart update (Flutter 1.7.8+hotfix.3) broke something and the Future never resolves when trying to get a photo from the Gallery or the Camera. Can someone help me do something to fix this? Thank you in advance!

D/skia    ( 6513): Shader compilation error
D/skia    ( 6513): ------------------------
D/skia    ( 6513): Errors:
D/skia    ( 6513): 
W/Binder  ( 6513): Caught a RuntimeException from the binder stub implementation.
W/Binder  ( 6513): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Binder:6513_1
W/Binder  ( 6513): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:794)
W/Binder  ( 6513): 	at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:727)
W/Binder  ( 6513): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:140)
W/Binder  ( 6513): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
W/Binder  ( 6513): 	at io.flutter.plugins.imagepickersaver.ImagePickerDelegate.finishWithSuccess(ImagePickerDelegate.java:515)
W/Binder  ( 6513): 	at io.flutter.plugins.imagepickersaver.ImagePickerDelegate.handleImageResult(ImagePickerDelegate.java:489)
W/Binder  ( 6513): 	at io.flutter.plugins.imagepickersaver.ImagePickerDelegate.access$000(ImagePickerDelegate.java:67)
W/Binder  ( 6513): 	at io.flutter.plugins.imagepickersaver.ImagePickerDelegate$4.onPathReady(ImagePickerDelegate.java:456)
W/Binder  ( 6513): 	at io.flutter.plugins.imagepickersaver.ImagePickerDelegate$3$1.onScanCompleted(ImagePickerDelegate.java:163)
W/Binder  ( 6513): 	at android.media.MediaScannerConnection$ClientProxy.onScanCompleted(MediaScannerConnection.java:204)
W/Binder  ( 6513): 	at android.media.MediaScannerConnection$1.scanCompleted(MediaScannerConnection.java:53)
W/Binder  ( 6513): 	at android.media.IMediaScannerListener$Stub.onTransact(IMediaScannerListener.java:61)
W/Binder  ( 6513): 	at android.os.Binder.execTransact(Binder.java:731)

**Comment by cetorres** [comment]
Same thing here.

**Comment by bhurlbert** [comment]
I stopped using _image_picker_saver_, and swapped it for just _image_picker_ because the app wasn't using the _save_ functions. It works now. Hopefully somebody is watching this issue and can followup and fix the issue here for those using the _save_ functions.

**Comment by cetorres** [comment]
@bhurlbert Yes, I also switched to image_picker for obtaining the image (camera or gallery). But image_picker doesn't have a method to save the photo (from camera) to the phone gallery. So I'm still using image_picker_saver just for saving. What are you using for saving the photo to the phone gallery?

**Comment by bhurlbert** [comment]
Hi @cetorres, i stopped saving the images because the app no longer needed that functionality right now.  What I'm doing in context to this use-case just fyi, is using the _file bytes_ and sending to our API where the file is stored on our servers after uploading.  In the past I used a combination of _path_provider_ and _Dart.io_ to write the file bytes to app's directory.  I hope that helps a little.
