### ISSUE TITLE
Save file fail in Android10.0

### ISSUE THREAD

**Issue by wys619** [cnhefang/image_picker_saver#28]
```log
2019-09-23 18:06:57.896 10818-10818/com.quwan.app.micgame_internal W/MediaStore: Failed to obtain thumbnail for content://media/external/images/media/2375
    java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
        at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:149)
        at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1711)
        at android.content.ContentResolver.openTypedAssetFile(ContentResolver.java:1616)
        at android.content.ContentResolver.lambda$loadThumbnail$0(ContentResolver.java:3614)
        at android.content.-$$Lambda$ContentResolver$7ILY1SWNxC2xhk-fQUG6tAXW9Ik.call(Unknown Source:10)
        at android.graphics.ImageDecoder$CallableSource.createImageDecoder(ImageDecoder.java:555)
        at android.graphics.ImageDecoder.decodeBitmapImpl(ImageDecoder.java:1859)
        at android.graphics.ImageDecoder.decodeBitmap(ImageDecoder.java:1852)
        at android.content.ContentResolver.loadThumbnail(ContentResolver.java:3613)
        at android.content.ContentResolver.loadThumbnail(ContentResolver.java:3597)
        at android.provider.MediaStore$InternalThumbnails.getThumbnail(MediaStore.java:1553)
        at android.provider.MediaStore$Images$Thumbnails.getThumbnail(MediaStore.java:1922)
        at io.flutter.plugins.imagepickersaver.CapturePhotoUtils.insertImage(CapturePhotoUtils.java:70)
        at io.flutter.plugins.imagepickersaver.ImagePickerDelegate.saveImageToGallery(ImagePickerDelegate.java:289)
        at io.flutter.plugins.imagepickersaver.ImagePickerSaverPlugin.onMethodCall(ImagePickerSaverPlugin.java:84)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:340)
        at android.os.Looper.loop(Looper.java:183)
        at android.app.ActivityThread.main(ActivityThread.java:7612)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1004)

```

**Comment by rdev-software** [comment]
Android 9, Samsung s9
writeImageDataToRequestedUri : failed to make directory

Intent is returned to app, but error method is not called, image is not provided
