### ISSUE TITLE
Save video file bug

### ISSUE THREAD

**Issue by dannyZhou** [cnhefang/image_picker_saver#4]
See: https://github.com/cnhefang/image_picker_saver/issues/2#issuecomment-449635010

Codes:
```dart

import 'package:http/http.dart' as oldHttp;
    String path = "http://example.com/generated.mp4";
    var response = await oldHttp.get(path);
    String filePath =
        await ImagePickerSaver.saveFile(fileData: response.bodyBytes);
```

Error Exception:
```

V/MediaStore( 6069): Create the thumbnail in memory: origId=373908, kind=1, isVideo=false
I/ExifInterface_JNI( 6069): Raw image not detected
W/ExifInterface( 6069): Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
W/ExifInterface( 6069): java.io.IOException: Invalid marker: 0
W/ExifInterface( 6069): 	at android.media.ExifInterface.getJpegAttributes(ExifInterface.java:1835)
W/ExifInterface( 6069): 	at android.media.ExifInterface.loadAttributes(ExifInterface.java:1475)
W/ExifInterface( 6069): 	at android.media.ExifInterface.<init>(ExifInterface.java:1112)
W/ExifInterface( 6069): 	at android.media.ThumbnailUtils.createThumbnailFromEXIF(ThumbnailUtils.java:480)
W/ExifInterface( 6069): 	at android.media.ThumbnailUtils.createImageThumbnail(ThumbnailUtils.java:97)
W/ExifInterface( 6069): 	at android.provider.MediaStore$InternalThumbnails.getThumbnail(MediaStore.java:759)
W/ExifInterface( 6069): 	at android.provider.MediaStore$Images$Thumbnails.getThumbnail(MediaStore.java:1091)
W/ExifInterface( 6069): 	at io.flutter.plugins.imagepickersaver.CapturePhotoUtils.insertImage(CapturePhotoUtils.java:70)
W/ExifInterface( 6069): 	at io.flutter.plugins.imagepickersaver.ImagePickerDelegate.saveImageToGallery(ImagePickerDelegate.java:285)
W/ExifInterface( 6069): 	at io.flutter.plugins.imagepickersaver.ImagePickerSaverPlugin.onMethodCall(ImagePickerSaverPlugin.java:84)
W/ExifInterface( 6069): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
W/ExifInterface( 6069): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handlePlatformMessage(FlutterNativeView.java:188)
W/ExifInterface( 6069): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
W/ExifInterface( 6069): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/ExifInterface( 6069): 	at android.os.MessageQueue.next(MessageQueue.java:323)
W/ExifInterface( 6069): 	at android.os.Looper.loop(Looper.java:142)
W/ExifInterface( 6069): 	at android.app.ActivityThread.main(ActivityThread.java:6358)
W/ExifInterface( 6069): 	at java.lang.reflect.Method.invoke(Native Method)
W/ExifInterface( 6069): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
W/ExifInterface( 6069): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
D/skia    ( 6069): --- SkAndroidCodec::NewFromStream returned null
```

**Comment by cnhefang** [comment]
This plugin not support to save a video file
